### ISSUE TITLE
Shield charge bar obstructs item's name

### ISSUE THREAD

**Issue by Auxioni** [Artistry-mods/amethyst-shield#10]
[Discord issue](https://discord.com/channels/1242139205044408410/1276271757380026458)
![Screenshot of the overlay issue](https://github.com/user-attachments/assets/d7a2fa0b-ed73-4b75-8855-29a478e7df9f)
As shown in the screenshot, the shield's ability charge bar overlays with the item's name when bubbles appear. This makes it hard to read longer item names at a glance. I suggest having the bar render below the item's name.

**Comment by HerrChaos** [comment]
Uhh no real idea how to do this. But could you please also put this issue in the discord server? So that I can track it easier.

**Comment by Auxioni** [comment]
Fixed in 2.1.7
